#
# jekyll config file for personal site
#

title: Samuel Rohrer
author: Samuel Rohrer
description: >
  personal website
logo: ./static/favicon.ico
google_analytics: UA-80135616-1

show_excerpts: false
show_downloads: false

github_username: srohrer32

minima:
  date_format: "%b %-d, %Y"

header_pages:
  - about.md

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
