#
# jekyll config file for personal site
#

title: Samuel Rohrer
author: Samuel Rohrer
email: samuel.rohrer@toptal.com
description: >
  personal website

show_excerpts: false
show_downloads: false

github_username: srohrer32

minima:
  date_format: "%b %-d, %Y"

header_pages:
  - links.md

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
