#
# jekyll config file for personal site
#

title: Samuel Rohrer
author: Samuel Rohrer
email: srohrer32@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  personal homepage, blog posts, links, work and recent news.
logo: static/favicon.ico
google_analytics: UA-80135616-1

show_excerpts: false # set to true to show excerpts on the homepage
show_downloads: false

github_username: srohrer32

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
